### ISSUE TITLE
Proposal: raise a custom error for JSON parse errors

### ISSUE THREAD

**Issue by NiklasHae** [unpoly/unpoly-rails#3]
Hi,

I'm trying to get rid of some notification noise that comes from https://github.com/unpoly/unpoly-rails/blob/7b29b62aa366693691dad426f95cfd78429969fb/lib/unpoly/rails/util.rb#L7 whenever `ActiveSupport::JSON.decode` is not able to parse JSON correctly and raises a `JSON::ParserError`. This happens when automatic security scanners try out different strings in the custom `unpoly-rails` headers.

Since the `JSON.parse_error` error is very generic, it's hard for me to specifically ignore or handle it globally. It would be way easier for me, if `unpoly-rails` would raise a simple custom error that `is_a` `Unpoly::Rails::Error`.

E.g.
```ruby
def json_decode(string)
  ActiveSupport::JSON.decode(string)
rescue ActiveSupport::JSON.parse_error
  raise MalformedHeaderError
end
```

Please let me know if you need help or more information :+1: Please feel free to close the issue if you don't agree with the proposal.

**Comment by triskweline** [comment]
We decided to no longer raise any errors when a client sends invalid JSON.

Released as `3.3.0.1`.
