### ISSUE TITLE
Brittle check if original_url contains _up_ query parameters

### ISSUE THREAD

**Issue by iaddict** [unpoly/unpoly-rails#4]
To decide if a URI contains \_up\_* parameters, a simple String#includes? check on the original url is made.
This causes an error on the following line, when the path compontent contains this prefix, but does not include any query parameters:

https://github.com/unpoly/unpoly-rails/blob/621a1ddcb7487f9f63c4b2ac28ff8be10dccff06/lib/unpoly/rails/change.rb#L282

```ruby
# this makes the following code fail, because the query is nil
URI.parse('https://example.com/sign_up_reminder/').query.split('&')
# => NoMethodError: undefined method `split' for nil:NilClass
```

**Comment by iaddict** [comment]
If you like me to propose a fix, I'll prepare a pull request.

**Comment by triskweline** [comment]
> If you like me to propose a fix, I'll prepare a pull request.

Yes, please!
