### ISSUE TITLE
Safe parsing of params

### ISSUE THREAD

**Issue by denzelem** [unpoly/unpoly-rails#9]
Security scanners causing `unpoly-rails` to fail on certain requests. It would be easier for a application integration to drop invalid requests instead of raising errors.

I created a [repository](https://github.com/denzelem/unpoly_rails_parse_error) to reproduce the issue. But I assume that all Rails application with `unpoly-rails` in the bundle will raise an error when calling `/?_up_context_changes={}&_up_events[$eq]=[]`.

Maybe the fix would be similar to https://github.com/unpoly/unpoly-rails/issues/3#issuecomment-1790799495, to not raise an error in case of invalid params?

**Comment by katrinwiedmann** [comment]
Any updates on this?

I'm having the same issue with a bot sending `/?_up_context_changes%5B%24acunetix%5D=1`. For some reason the `ActionController::Parameters` object is passed to https://github.com/unpoly/unpoly-rails/blob/aac9b0922013b60b0a272759f7e676cda2c4e010/lib/unpoly/rails/util.rb#L6 resulting in a TypeError(no implicit conversion of ActionController::Parameters into String) when passing it to `ActiveSupport::JSON.decode(raw)` in line 9.

**Comment by triskweline** [comment]
Fixed in 3.9.2.1.
